stages:
 - test
 - deploy

# Job to run tests for clustering
test_job:
 stage: test
 script:
 - tox # This will run the tests for clustering

# Job to deploy the clustering model
deploy_job:
 stage: deploy
 script:
 - tox -e deploy # This will run the deployment for clustering
 
